# Generated by Django 5.2.5 on 2025-08-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
