# Generated by Django 5.2.5 on 2025-08-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparts', '0002_alter_sparepart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cars'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part', to='carparts.car'),
        ),
    ]
